/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as HubProgramRouteImport } from './routes/hub.$program'
import { Route as WorksheetIdRouteImport } from './routes/worksheet.$id'
import { Route as ExamProgramSubjectYearRouteImport } from './routes/exam.$program.$subject.$year'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const HubProgramRoute = HubProgramRouteImport.update({
  id: '/hub/$program',
  path: '/hub/$program',
  getParentRoute: () => rootRouteImport,
} as any)
const WorksheetIdRoute = WorksheetIdRouteImport.update({
  id: '/worksheet/$id',
  path: '/worksheet/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamProgramSubjectYearRoute = ExamProgramSubjectYearRouteImport.update({
  id: '/exam/$program/$subject/$year',
  path: '/exam/$program/$subject/$year',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/programs': typeof ProgramsRoute
  '/hub/$program': typeof HubProgramRoute
  '/worksheet/$id': typeof WorksheetIdRoute
  '/exam/$program/$subject/$year': typeof ExamProgramSubjectYearRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/programs': typeof ProgramsRoute
  '/hub/$program': typeof HubProgramRoute
  '/worksheet/$id': typeof WorksheetIdRoute
  '/exam/$program/$subject/$year': typeof ExamProgramSubjectYearRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/programs': typeof ProgramsRoute
  '/hub/$program': typeof HubProgramRoute
  '/worksheet/$id': typeof WorksheetIdRoute
  '/exam/$program/$subject/$year': typeof ExamProgramSubjectYearRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/leaderboard'
    | '/login'
    | '/programs'
    | '/hub/$program'
    | '/worksheet/$id'
    | '/exam/$program/$subject/$year'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/leaderboard'
    | '/login'
    | '/programs'
    | '/hub/$program'
    | '/worksheet/$id'
    | '/exam/$program/$subject/$year'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/leaderboard'
    | '/login'
    | '/programs'
    | '/hub/$program'
    | '/worksheet/$id'
    | '/exam/$program/$subject/$year'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  DashboardRoute: typeof DashboardRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LoginRoute: typeof LoginRoute
  ProgramsRoute: typeof ProgramsRoute
  HubProgramRoute: typeof HubProgramRoute
  WorksheetIdRoute: typeof WorksheetIdRoute
  ExamProgramSubjectYearRoute: typeof ExamProgramSubjectYearRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub/$program': {
      id: '/hub/$program'
      path: '/hub/$program'
      fullPath: '/hub/$program'
      preLoaderRoute: typeof HubProgramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/worksheet/$id': {
      id: '/worksheet/$id'
      path: '/worksheet/$id'
      fullPath: '/worksheet/$id'
      preLoaderRoute: typeof WorksheetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam/$program/$subject/$year': {
      id: '/exam/$program/$subject/$year'
      path: '/exam/$program/$subject/$year'
      fullPath: '/exam/$program/$subject/$year'
      preLoaderRoute: typeof ExamProgramSubjectYearRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  DashboardRoute: DashboardRoute,
  LeaderboardRoute: LeaderboardRoute,
  LoginRoute: LoginRoute,
  ProgramsRoute: ProgramsRoute,
  HubProgramRoute: HubProgramRoute,
  WorksheetIdRoute: WorksheetIdRoute,
  ExamProgramSubjectYearRoute: ExamProgramSubjectYearRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
